{{- if .Values.app.autoscaling.enabled }}
{{- $as := .Values.app.autoscaling }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kodbox.componentName" (dict "ctx" . "component" "app") }}
  namespace: {{ include "kodbox.namespace" $ }}
  labels:
    {{- include "kodbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: app
  {{- include "kodbox.annotations" (dict "ctx" $ "extra" nil) | nindent 2 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kodbox.componentName" (dict "ctx" . "component" "app") }}
  minReplicas: {{ $as.minReplicas }}
  maxReplicas: {{ $as.maxReplicas }}
  metrics:
    {{- with $as.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
    {{- with $as.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ . }}
    {{- end }}
  {{- with $as.behavior }}
  behavior:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
