{{- if and .Values.backup.enabled (not .Values.backup.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "kodbox.componentName" (dict "ctx" . "component" "backup") }}
  namespace: {{ include "kodbox.namespace" $ }}
  labels:
    {{- include "kodbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: backup
  {{- include "kodbox.annotations" (dict "ctx" $ "extra" (merge (dict "helm.sh/resource-policy" "keep") (.Values.backup.persistence.annotations | default dict))) | nindent 2 }}
spec:
  accessModes:
    {{- toYaml .Values.backup.persistence.accessModes | nindent 4 }}
  {{- include "kodbox.storageClass" (dict "ctx" $ "sc" .Values.backup.persistence.storageClass) | nindent 2 }}
  resources:
    requests:
      storage: {{ .Values.backup.persistence.size }}
{{- end }}
