{{- if and (not .Values.redis.enabled) .Values.externalRedis.password (not .Values.externalRedis.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kodbox.componentName" (dict "ctx" . "component" "redis") }}
  labels:
    {{- include "kodbox.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.externalRedis.password | quote }}
{{- end }}
