name: Feature request
description: Suggest an option or improvement for the chart
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What do you want to do that the chart doesn't support?
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: How would you like it to work?
      description: For example, the values you'd set.
