"""Generates the "All values" reference in charts/kodbox/README.md.

Descriptions come from values.schema.json (see gen_values_schema.py), defaults
from values.yaml. Run after changing either:

    python3 scripts/gen_values_schema.py && python3 scripts/gen_values_doc.py
"""
import json
import pathlib

import yaml

CHART = pathlib.Path(__file__).resolve().parent.parent / "charts" / "kodbox"
START = "<!-- values:start (generated by scripts/gen_values_doc.py, do not edit) -->"
END = "<!-- values:end -->"


def fmt_default(value):
    if value is None:
        return ""
    text = json.dumps(value, separators=(", ", ": "))
    if len(text) > 60:
        text = text[:57] + "..."
    return "`" + text.replace("|", "\\|") + "`"


def fmt_type(schema):
    t = schema.get("type", "")
    if isinstance(t, list):
        t = " / ".join(t)
    if "enum" in schema:
        t = " \\| ".join(json.dumps(e) for e in schema["enum"])
    return t


def rows(schema, values, path):
    """Leaf keys: properties without sub-properties (free-form objects included)."""
    for key, sub in schema.get("properties", {}).items():
        sub_path = f"{path}.{key}" if path else key
        sub_value = values.get(key) if isinstance(values, dict) else None
        if "properties" in sub and sub["properties"]:
            yield from rows(sub, sub_value, sub_path)
        else:
            desc = sub.get("description", "").replace("|", "\\|").replace("\n", " ")
            yield f"| `{sub_path}` | {fmt_type(sub)} | {fmt_default(sub_value)} | {desc} |"


def main():
    schema = json.loads((CHART / "values.schema.json").read_text())
    values = yaml.safe_load((CHART / "values.yaml").read_text())
    out = [START, ""]
    for key, sub in schema["properties"].items():
        if key == "global" and not values.get("global"):
            continue
        out.append(f"### {key}")
        out.append("")
        if sub.get("description"):
            out.append(sub["description"])
            out.append("")
        out.append("| Key | Type | Default | Description |")
        out.append("|---|---|---|---|")
        if "properties" in sub and sub["properties"]:
            out.extend(rows(sub, values.get(key), key))
        else:
            out.append(f"| `{key}` | {fmt_type(sub)} | {fmt_default(values.get(key))} | {sub.get('description', '')} |")
        out.append("")
    out.append(END)

    readme = CHART / "README.md"
    text = readme.read_text()
    start, end = text.index(START), text.index(END) + len(END)
    readme.write_text(text[:start] + "\n".join(out) + text[end:])
    print(f"wrote {readme}")


if __name__ == "__main__":
    main()
